# infra/patches/gateway-api-crds.yaml
cluster:
  inlineManifests:
    - name: gateway-api-crds
      contents: |
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: gatewayclasses.gateway.networking.k8s.io
          annotations:
            api-approved.kubernetes.io: "https://github.com/kubernetes-sigs/gateway-api/pull/2950"
        spec:
          group: gateway.networking.k8s.io
          names:
            kind: GatewayClass
            listKind: GatewayClassList
            plural: gatewayclasses
            singular: gatewayclass
          scope: Cluster
          versions:
            - name: v1
              served: true
              storage: true
              subresources:
                status: {}
        ---
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: gateways.gateway.networking.k8s.io
        spec:
          group: gateway.networking.k8s.io
          names:
            kind: Gateway
            listKind: GatewayList
            plural: gateways
            singular: gateway
          scope: Namespaced
          versions:
            - name: v1
              served: true
              storage: true
              subresources:
                status: {}
        ---
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: httproutes.gateway.networking.k8s.io
        spec:
          group: gateway.networking.k8s.io
          names:
            kind: HTTPRoute
            listKind: HTTPRouteList
            plural: httproutes
            singular: httproute
          scope: Namespaced
          versions:
            - name: v1
              served: true
              storage: true
              subresources:
                status: {}
        ---
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: referencegrants.gateway.networking.k8s.io
        spec:
          group: gateway.networking.k8s.io
          names:
            kind: ReferenceGrant
            listKind: ReferenceGrantList
            plural: referencegrants
            singular: referencegrant
          scope: Namespaced
          versions:
            - name: v1beta1
              served: true
              storage: true
        ---
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: grpcroutes.gateway.networking.k8s.io
        spec:
          group: gateway.networking.k8s.io
          names:
            kind: GRPCRoute
            listKind: GRPCRouteList
            plural: grpcroutes
            singular: grpcroute
          scope: Namespaced
          versions:
            - name: v1
              served: true
              storage: true
              subresources:
                status: {}
        ---
        apiVersion: apiextensions.k8s.io/v1
        kind: CustomResourceDefinition
        metadata:
          name: tlsroutes.gateway.networking.k8s.io
        spec:
          group: gateway.networking.k8s.io
          names:
            kind: TLSRoute
            listKind: TLSRouteList
            plural: tlsroutes
            singular: tlsroute
          scope: Namespaced
          versions:
            - name: v1alpha2
              served: true
              storage: true
              subresources:
                status: {}