# apps/argocd/argocd/git-pat-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: github-pat-repo
  namespace: argocd
  labels:
    # This label is CRITICAL for ArgoCD to recognize it as a repository credential.
    argocd.argoproj.io/secret-type: repository
stringData:
  # The URL MUST match the repoURL defined in your ApplicationSet
  url: "https://github.com/RogueStarr/contrib.git"
  username: "Roguito" # Your GitHub username
  password: "uAxFqdnzVaW7BZr1VIg8Z3PFVhXAnyhFzmmo_BOa" # Your GitHub PAT